### ISSUE TITLE
Standardisation Requests

### ISSUE THREAD

**Issue by saranonearth** [pyk/zkevm-wsteth#1]
Few standards that are requested to be considered,
- Implementation similar to [this](https://github.com/0xPolygonHermez/code-examples/blob/main/customERC20-bridge-example/contracts/lib/PolygonBridgeLib.sol) using the PolygonBridgeLib
- Can please make [L2wstETH.sol](https://github.com/pyk/zkevm-wsteth/blob/main/src/L2wstETH.sol) a separate contract and ERC20(wrapped token) a separate contract
- Expose following variables in both L1 and L2 contracts,
    1. originTokenAddress: Address of the native token
    2. originTokenNetwork: networkId of the chain where the token is a native token (0 is the networkId for ethereum, 1 is the networkId ZkEVM)
    3. wrappedTokenAddress: Address of the wrapped token address

**Comment by pyk** [comment]
Hi @saranonearth, thank you so much for the review. 🙏

I have made some changes based on your feedback:

- I refactored `L1Escrow` to [`MainnetBridge`](https://github.com/pyk/zkevm-wsteth/blob/main/src/MainnetBridge.sol) and used an upgradeable version of [`PolygonERC20BridgeLib`](https://github.com/pyk/zkevm-wsteth/blob/main/src/PolygonERC20BridgeLibUpgradeable.sol).
- Now, `MainnetBridge` exposes the following variables:
  - `originTokenAddress`
  - `originTokenNetwork`

I have a question regarding this part:

> Can please make [L2wstETH.sol](https://github.com/pyk/zkevm-wsteth/blob/main/src/L2wstETH.sol) a separate contract and ERC20(wrapped token) a separate contract

Are you suggesting that we create two contracts: `zkEVMBridge.sol` and `wstETH.sol`, where `zkEVMBridge` acts as the minter and burner of `wstETH` ERC20 tokens?

>Expose following variables in both L1 and L2 contracts,
>originTokenAddress: Address of the native token
>originTokenNetwork: networkId of the chain where the token is a native token (0 is the networkId for ethereum, 1 is the >networkId ZkEVM)
>wrappedTokenAddress: Address of the wrapped token address

Regarding the `wrappedTokenAddress`, could you please clarify the difference between `originTokenAddress` and `wrappedTokenAddress`?

Since `MainnetBridge` only escrows the token, does it mean that `wrappedTokenAddress` should be set to `0x0`?

**Comment by saranonearth** [comment]
Hey, sorry for the delay,
> Are you suggesting that we create two contracts: zkEVMBridge.sol and wstETH.sol, where zkEVMBridge acts as the minter and burner of wstETH ERC20 tokens?

Yes, and let zkEVMBridge have the info of `wrappedTokenAddress`, `wrappedTokenAddress`, `originTokenNetwork`

> Regarding the wrappedTokenAddress, could you please clarify the difference between originTokenAddress and wrappedTokenAddress?

`originTokenAddress` - Address of the token on the chain it is a native token
`originTokenNetwork` - NetworkId of the chain where it is a native token
`wrappedTokenAddress` - Address of the wrapped token

Example for USDC

`originTokenAddress` - 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
`originTokenNetwork` - 0
`wrappedTokenAddress` - 0xA8CE8aee21bC2A48a5EF670afCc9274C7bbbC035

> Since MainnetBridge only escrows the token, does it mean that wrappedTokenAddress should be set to 0x0?
No, we can set the `wrappedTokenAddress` to the address of the token in zkevm.

Feel free to let me know if you have more queries. Thanks

**Comment by pyk** [comment]
Thank you so much, @saranonearth, for the clarification. It's incredibly helpful. 🙏

I've refactored the contracts to align with the provided specifications and standards.

Here is a quick summary of each contract:

1. `WstETHWrapped` (ERC20 with ERC-2612 extension)
    - Will be deployed on Polygon zkEVM Mainnet
    - Upgradeable
    - Pausable
    - Have 2 roles: Admin & Emergency
        - Admin can upgrade, cannot pause
        - Emergency role cannot upgrade, can pause
        - Token is non-transferable when paused
    - `WstETHBridgeL2` can mint and burn the token
2. `WstETHBridgeL2`
    - Will be deployed on Polygon zkEVM Mainnet
    - Upgradeable
    - Pausable
    - Have 2 roles: Admin & Emergency
        - Admin can upgrade, cannot pause
        - Emergency role cannot upgrade, can pause
        - Cannot bridge token to Ethereum mainnet when paused
    - Expose public variables:
        -  `originTokenAddress=0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0` -> wstETH address on mainnet 
        - `wrappedTokenAddress` -> wstETHWrapped address on polygon zkevm
        - Expose public variable `originTokenNetwork = 0` 
3. `WstETHBridgeL1`
    - Will be deployed on Ethereum Mainnet
    - Upgradeable
    - Pausable
    - Have 2 roles: Admin & Emergency
         - Admin can upgrade, cannot pause
         - Emergency role cannot upgrade, can pause
    - Expose public variables:
        -  `originTokenAddress=0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0` -> wstETH address on mainnet 
        - `wrappedTokenAddress` -> wstETHWrapped address on polygon zkevm
        - Expose public variable `originTokenNetwork = 0` 


`WstETHBridgeL1` and `WstETHBridgeL2` use [PolygonERC20BridgeLibUpgradeable.sol](https://github.com/pyk/zkevm-wsteth/blob/main/src/base/PolygonERC20BridgeLibUpgradeable.sol) which upgradeable version of PolygonERC20BridgeLib.sol

The `zkevm-wsteth` project is ready for review now 🙏

**Comment by saranonearth** [comment]
Looks good, @pyk

**Comment by pyk** [comment]
ty @saranonearth, I will close this issue
